package universityManagementSystem.enums.academic;

public enum MasterProgram {
    DATA_SCIENCE, IT_MANAGEMENT, SOFTWARE_ENGINEERING, COMPUTER_SCIENCE_AND_DATA_ANALYTICS, INFORMATION_SYSTEMS,
    INDUSTRIAL_AND_SYSTEMS_ENGINEERING, ELECTRONICS_AND_CONTROL_SYSTEMS, SMART_CITIES_AND_SMART_SYSTEMS
}
