package main.java.kbtu.chill_guys.university_management_system.enumeration.academic;

public enum MasterProgram implements Program {
    DATA_SCIENCE, IT_MANAGEMENT, SOFTWARE_ENGINEERING, COMPUTER_SCIENCE_AND_DATA_ANALYTICS, INFORMATION_SYSTEMS,
    INDUSTRIAL_AND_SYSTEMS_ENGINEERING, ELECTRONICS_AND_CONTROL_SYSTEMS, SMART_CITIES_AND_SMART_SYSTEMS
}
